[pytest]
addopts =
    -v
    -s
    --html=reports/report.html
    --self-contained-html

testpaths =
    Tests

python_files =
    test_*.py

python_classes = Test* Demo*

python_functions = test_* check_*

markers =
    smoke: Smoke tests
    regression: Regression tests
    sanity: Sanity tests
    p0: P0 tests
    p1: P1 tests
    rest_api_sanity: Rest API tests

log_cli = true
log_cli_level = INFO
log_file = logs/test.log
log_file_level = DEBUG